services:
  frontend:
    build: ./bed-con
    container_name: frontend
    command: gunicorn -b 0.0.0.0:8000 app:app --timeout 120 --workers 2 --threads 2
    ports:
      - "80:8000"
    depends_on:
      - chatbot
    restart: always

  chatbot:
    build: ./chatbot
    container_name: chatbot
    expose:
      - "5001"
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    restart: always
